### ISSUE TITLE
Webpack is a runtime dependency?

### ISSUE THREAD

**Issue by MaxWilson** [pepaar/typescript-webpack-react-redux-boilerplate#11]
With the boilerplate, npm start runs webpack. So if I push the boilerplate out as an Azure app running under iisnode, I'll get a 500/Internal Server Error because webpack is not installed.

How do I alter the template to make webpack a compile-time dependency online instead of runtime?

**Comment by pepaar** [comment]
Webpack is only a tool to build client side code and webpack-dev-server is just for development purpose. If you want to deploy the app to Azure you need a server which serves the page where you reference built JavaScript files (with npm run build).

**Comment by MaxWilson** [comment]
Ah, I see. I had misunderstood the scope of the boilerplate.
