### ISSUE TITLE
Images are not loaded..

### ISSUE THREAD

**Issue by hitesh97** [pepaar/typescript-webpack-react-redux-boilerplate#14]
Hi there,
I am trying to use your typescript webpack teact starter project..and its great repo for starting point.. thanks for sharing and hosting the code..
However i am unable to use it for images...
Meaning if i use 
< img src="someimage.jpg" /> 
In my comppnent.. and the image exists in the same folder as the component.. it stll doesnt show...

I have tried to use 
< img src="/assets/someimage.jpg" /> 
 as a path and 

also tried to use 
"import statement in the component.tsx... 

e.g import img from "./someimage.jpg"

but none of the above options work ..

Can you please show me with example how to achieve this?

Thanks a million.

**Comment by pepaar** [comment]
This pull request adds example how to use image #15

**Comment by hitesh97** [comment]
Hi Pepaar,
Thanks for showing the example in the pull request above.
I have tried this option, however the typescript compiler is complaining and giving me following error.

error TS2322: Type '{}' is not assignable to type 'string'.

I am using latest version of typescript..

can you please help?

Regards,
Hitesh
