### ISSUE TITLE
Trying to follow the getting started guide

### ISSUE THREAD

**Issue by murugaratham** [pepaar/typescript-webpack-react-redux-boilerplate#16]
Hi Petar,

I tried the following:

- run npm install to download dependencies
- run npm start to build and start webpack-dev-server
- open http://localhost:3333/

But i am getting the following message:

`error TS2322: Type '{}' is not assignable to type 'string'`

My environments are:

$ node -v
v6.9.1

$ npm -v
3.10.8

**Comment by pepaar** [comment]
The issue is fixed with #17
