### ISSUE TITLE
Dev mode loads multiple copies of the dependencies

### ISSUE THREAD

**Issue by atifsyedali** [pepaar/typescript-webpack-react-redux-boilerplate#4]
You need to put 

```
    new webpack.optimize.CommonsChunkPlugin('vendors', 'vendors.js'),
```

in webpack.dev.config.js, otherwise in development mode you end up loading two copies of all dependencies ... one in app.js and one in vendor.js.

I found this out painfully when adding jquery and some jquery plugins. The jquery library would get loaded in vendor.js, along with other jquery plugins. Additionally, jquery plugins would correctly be supplied a jquery object, however, later on when app.js loads, it loads another jquery copy. Thus, none of the plugins that were added to the vendor.js' jquery were there.

**Comment by pepaar** [comment]
Thanks! Fixed with https://github.com/pepaar/typescript-webpack-react-flux-boilerplate/commit/2a937cd8ee081c7016a84d4942db733567bd87bd
