### ISSUE TITLE
tsd is deprecated use typings and typings.json

### ISSUE THREAD

**Issue by Ciantic** [pepaar/typescript-webpack-react-redux-boilerplate#6]
tsd is deprecated (it says so if you run it) and is replaced with npm package called typings.

It does however raise a bigger problems perhaps, because typings create type definitions for node and browser separately (in different directories) so it may require more changes than just a tool.

**Comment by Ciantic** [comment]
This is not a pull request but I made a change to typings if you are interested: https://github.com/Ciantic/typescript-webpack-react-flux-boilerplate

I also found out that if I add to tsconfig.json the exclusion:

```
{
    "compilerOptions": {
        "target": "es6",
        "sourceMap": true,
        "jsx": "react"
    },
    "exclude": [
        "node_modules",
        "typings/main.d.ts",
        "typings/main"
    ]
}
```

I can leave out all of the `<reference` tags without errors! (Except one in index.tsx)

_Edit_ Noticed that test files still have to have the reference tags, but it's mighty reduction. I wonder if it's possible to have one ts file for tests that contain the single reference tag which is included in karma conf before the other test files, this way it wouldn't be required in test files either.

**Comment by pepaar** [comment]
Thanks on your comment. I was planning to use typings instead of tsd but didn't catch time yet. I will check your fork and see if I can reuse it. 
Regarding one file which references d.ts, you can try to require it at the start of karma.tests.js file.

**Comment by pepaar** [comment]
Switched to npm for definition files as part of move to Typescript 2.0 -  https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

#12
