### ISSUE TITLE
.ts files are not reloaded, simple fix

### ISSUE THREAD

**Issue by Ciantic** [pepaar/typescript-webpack-react-redux-boilerplate#7]
Noticed that .ts files are not reloaded, easy fix open webpack.config.js and webpack.dev.config.js, replace `test: /\.ts(x?)$/` with `test: /\.tsx?$/`

Not sure why regexp groups are not working in webpack test rule, but they just don't.

**Comment by pepaar** [comment]
Thanks. Could be some OS issue? Which OS are you running? I'm running on windows and it works fine..

**Comment by Ciantic** [comment]
I can't replicate this problem anymore. Also on Windows. It may have been some other issue, and I just thought this fixed it when it was something else.
